[package]
name = "log_hawk"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.27"
eframe = "0.27"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.14", features = ["json"] }
serde = { version = "1", features = ["derive"] }
